[package]
name = "katniss-parquet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parquet = "32.0.0"
katniss-pb2arrow = { path = "../katniss-pb2arrow" }
thiserror = "1.0.38"
