[package]
name = "prost-arrow-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.6"
prost-reflect = "0.10.1"

[build-dependencies]
prost-build = "0.11.6"
