[package]
name = "katniss-ingestor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parquet = "34.0.0"
katniss-pb2arrow = { path = "../katniss-pb2arrow" }
thiserror = "1.0.38"
arrow-schema = "34.0.0"
itertools = "0.10.5"
